### ISSUE TITLE
mGameBits throwing a syntax error

### ISSUE THREAD

**Issue by ForgotPants** [MCn-/gamebits#11]
I was trying to scrape a game but kept getting a syntax error, here is what it is,

File "e:\path to mGamebits folder\mGameBits.py", line 122
print "Game Name: " + proper_game_title.encode('utf-8')

Syntax Error: invalid syntax

On the second line of the error, the one starting with print, there is a small arrow pointing at the second double quotes.

Any idea whats wrong? Am I not using it correctly?

**Comment by MCn-** [comment]
I've updated the code, please re-open this if you are still encountering errors.
