### ISSUE TITLE
Win7: AttributeError: 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by kroak** [MCn-/gamebits#12]
C:\Users\###\Documents\BaconBits\mGameBits\gamebits-mGameBits>"C:\Pyth
on27\python.exe" mGameBits.py http://www.mobygames.com/game/civilization-call-to
-power   1>>blah.txt
Traceback (most recent call last):
  File "mGameBits.py", line 86, in <module>
    proper_game_title = soup.find('div', id='gameTitle').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'

C:\Users\####\Documents\BaconBits\mGameBits\gamebits-mGameBits>pause
Press any key to continue . . .

**Comment by MCn-** [comment]
This should now be fixed.
